name: test_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - expat=2.6.4=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=25.0=py312haa95532_0
  - python=3.12.8=h14ffc60_0
  - setuptools=75.8.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - tzdata=2025a=h04d1e81_0
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wheel=0.44.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.115.7
      - fastapi-cli==0.0.7
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.5
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.45.3
      - typer==0.15.1
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - watchfiles==1.0.4
      - websockets==14.2
prefix: C:\Users\NickW\miniconda3\envs\test_env
